parameters:
#    cyniris_syndicate.example.class: Cyniris\SyndicateBundle\Example

services:
#    cyniris_syndicate.example:
#        class: %cyniris_syndicate.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
